/**********************************************************************************************************************
 * \file core_event.c
 * \copyright Copyright (C) Roy Ratcliffe, 2025. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "core_event.h"
#include "event_group.h"
#include "when.h"

#include "Compilers.h"
#include "IfxCpu.h"

#include <errno.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

WHEN(core0_event0);
WHEN(core0_event1);
WHEN(core0_event2);
WHEN(core0_event3);
WHEN(core0_event4);
WHEN(core0_event5);
WHEN(core0_event6);
WHEN(core0_event7);
WHEN(core0_event8);
WHEN(core0_event9);
WHEN(core0_event10);
WHEN(core0_event11);
WHEN(core0_event12);
WHEN(core0_event13);
WHEN(core0_event14);
WHEN(core0_event15);
WHEN(core0_event16);
WHEN(core0_event17);
WHEN(core0_event18);
WHEN(core0_event19);
WHEN(core0_event20);
WHEN(core0_event21);
WHEN(core0_event22);
WHEN(core0_event23);
WHEN(core0_event24);
WHEN(core0_event25);
WHEN(core0_event26);
WHEN(core0_event27);
WHEN(core0_event28);
WHEN(core0_event29);
WHEN(core0_event30);
WHEN(core0_event31);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*!
 * \brief Event groups for each core.
 * \details This array holds the event groups for each core in the system.
 * Each core has its own event group used for synchronisation.
 * \note The size of the array is determined by the number of CPU modules
 * defined by the \c IFXCPU_NUM_MODULES manifest constant.
 * \note The array lives in blank static storage and is zero-initialised at startup.
 * \see event_group_t
 */
static event_group_t event_group[IFXCPU_NUM_MODULES];

static const struct {
  void (*const *start_of_when)(void *with, ...);
  void (*const *end_of_when)(void *with, ...);
} core_clz[IFXCPU_NUM_MODULES][32] = {
    /* core 0 */
    {{START_OF_WHEN(core0_event0), END_OF_WHEN(core0_event0)},   {START_OF_WHEN(core0_event1), END_OF_WHEN(core0_event1)},
     {START_OF_WHEN(core0_event2), END_OF_WHEN(core0_event2)},   {START_OF_WHEN(core0_event3), END_OF_WHEN(core0_event3)},
     {START_OF_WHEN(core0_event4), END_OF_WHEN(core0_event4)},   {START_OF_WHEN(core0_event5), END_OF_WHEN(core0_event5)},
     {START_OF_WHEN(core0_event6), END_OF_WHEN(core0_event6)},   {START_OF_WHEN(core0_event7), END_OF_WHEN(core0_event7)},
     {START_OF_WHEN(core0_event8), END_OF_WHEN(core0_event8)},   {START_OF_WHEN(core0_event9), END_OF_WHEN(core0_event9)},
     {START_OF_WHEN(core0_event10), END_OF_WHEN(core0_event10)}, {START_OF_WHEN(core0_event11), END_OF_WHEN(core0_event11)},
     {START_OF_WHEN(core0_event12), END_OF_WHEN(core0_event12)}, {START_OF_WHEN(core0_event13), END_OF_WHEN(core0_event13)},
     {START_OF_WHEN(core0_event14), END_OF_WHEN(core0_event14)}, {START_OF_WHEN(core0_event15), END_OF_WHEN(core0_event15)},
     {START_OF_WHEN(core0_event16), END_OF_WHEN(core0_event16)}, {START_OF_WHEN(core0_event17), END_OF_WHEN(core0_event17)},
     {START_OF_WHEN(core0_event18), END_OF_WHEN(core0_event18)}, {START_OF_WHEN(core0_event19), END_OF_WHEN(core0_event19)},
     {START_OF_WHEN(core0_event20), END_OF_WHEN(core0_event20)}, {START_OF_WHEN(core0_event21), END_OF_WHEN(core0_event21)},
     {START_OF_WHEN(core0_event22), END_OF_WHEN(core0_event22)}, {START_OF_WHEN(core0_event23), END_OF_WHEN(core0_event23)},
     {START_OF_WHEN(core0_event24), END_OF_WHEN(core0_event24)}, {START_OF_WHEN(core0_event25), END_OF_WHEN(core0_event25)},
     {START_OF_WHEN(core0_event26), END_OF_WHEN(core0_event26)}, {START_OF_WHEN(core0_event27), END_OF_WHEN(core0_event27)},
     {START_OF_WHEN(core0_event28), END_OF_WHEN(core0_event28)}, {START_OF_WHEN(core0_event29), END_OF_WHEN(core0_event29)},
     {START_OF_WHEN(core0_event30), END_OF_WHEN(core0_event30)}, {START_OF_WHEN(core0_event31), END_OF_WHEN(core0_event31)}},
    /* core 1 */
};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

static void sync(int clz, va_list va);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

int core_event_signal(int core, int clz) {
  if (core < 0 || core >= IFXCPU_NUM_MODULES) {
    return -EINVAL;
  }
  event_group_signal(event_group + core, clz);
  return 0;
}

int core_event_sync(void) {
  int core = IfxCpu_getCoreId();
  if (core < 0 || core >= IFXCPU_NUM_MODULES) {
    return -EINVAL;
  }
  event_group_sync(&event_group[core], sync, core);
  return 0;
}

static void sync(int clz, va_list va) {
  const int core = va_arg(va, int);
  switch (core) {
  case 0:
    OCCURS(core0_event, (void *)clz);
    break;
  case 1:
    OCCURS(core1_event, (void *)clz);
    break;
  case 2:
    OCCURS(core2_event, (void *)clz);
    break;
  default:
    return;
  }
  for (void (*const *when_func)(void *with, ...) = core_clz[core][clz].start_of_when; when_func < core_clz[core][clz].end_of_when; when_func++) {
    (*when_func)(NULL_PTR);
  }
}
